[workspace]
resolver = "2"
members = [
    "packages/aqueduct",
    "packages/multibytes",
    "packages/qkai",
]

[workspace.dependencies]
multibytes = { path = "packages/multibytes" }
qkai = { path = "packages/qkai" }

anyhow = "1"
bytes = "1"
dashmap = "6"
ed25519-dalek = "2"
quinn = "0.11"
rand = "0.9"
rcgen = "0.14"
rustls = "0.23"
serde = "1"
serde_json = "1"
thiserror = "2"
tracing = "0.1"
x509-parser = "0.18"

[workspace.dependencies.tokio]
version = "1"
default-features = false
