[package]
name = "aqueduct"
version = "0.0.0-AFTER"
edition = "2021"
publish = false

[dependencies]
bytes = "1"
smallvec = "1"
dashmap = "6"
quinn = "0.11"
anyhow = "1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync", "rt", "time"]

[dev-dependencies]
rand = "0.8"
rand_pcg = "0.3"
