[package]
name = "aqueduct"
version = "0.0.0-AFTER"
edition = "2021"
publish = false

[features]

[dependencies]
bytes = "1"
smallvec = "1"
dashmap = "6"
quinn = "0.11"
anyhow = "1"
thiserror = "2"
rcgen = "0.13"
tracing = "0.1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["rt", "sync"]

[dev-dependencies]
rand = "0.8"
rand_pcg = "0.3"
